[package]
name = "linecount"
version = "0.1.0"
authors = ["Erik Clarke <erikclarke@fastmail.com>"]
license = "GPL-3"
description = "Quickly count lines in a file"

[dependencies]

[[bin]]
name = "lc"
path = "src/lc.rs"